Install required pacckages to work

In [1]:
!pip install -r ../Classification/requirements.txt

In [2]:
import sys
import os
sys.modules.pop('dataset_split', None)  # Replace with your module name

In [4]:
current_path = os.getcwd()
print(current_path)

c:\Users\carol\Documents\IPCV-MASTER\TRDP\SalUn_study\My_tests


In [5]:
from dataset_split import *

root_dataset = current_path + '/datasets/'
ds = UnlearnDatasetSplit(root_dataset, "cifar10")

100%|██████████| 170498071/170498071 [03:11<00:00, 889985.35it/s] 


Extracting c:\Users\carol\Documents\IPCV-MASTER\TRDP\SalUn_study\My_tests/datasets/cifar-10-python.tar.gz to c:\Users\carol\Documents\IPCV-MASTER\TRDP\SalUn_study\My_tests/datasets/
Files already downloaded and verified
Classes: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


In [199]:
splitted = ds.split_dataset("class", True, forget=['cat', 'frog'])
print(splitted)

['cat', 'frog']
is list
is string list
class is [3 6]
{'Train': Dataset CIFAR10
    Number of datapoints: 50000
    Root location: c:\Users\carol\Documents\IPCV-MASTER\TRDP\Code\SalUn_study\My_tests/datasets/
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
           ), 'Test': Dataset CIFAR10
    Number of datapoints: 10000
    Root location: c:\Users\carol\Documents\IPCV-MASTER\TRDP\Code\SalUn_study\My_tests/datasets/
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
           ), 'Train_retain': <torch.utils.data.dataset.Subset object at 0x00000199007EF010>, 'Train_forget': <torch.utils.data.dataset.Subset object at 0x000001990075DA50>, 'Test_retain': <torch.utils.data.dataset.Subset object at 0x000001990075C990>, 'Test_forget': <torch.utils.data.dataset.S

In [6]:
splitted = ds.load_dataset()

['Test.pkl', 'Test_forget.pkl', 'Test_retain.pkl', 'Train.pkl', 'Train_forget.pkl', 'Train_retain.pkl']


In [7]:
tf = ds.get_loader("Train_forget", batchsize=64)


In [8]:
print(tf)

In [191]:
sys.path.append("c:/Users/carol/Documents/IPCV-MASTER/TRDP/Code/SalUn_study/Classification")
print(sys.path)

['c:\\Users\\carol\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip', 'c:\\Users\\carol\\AppData\\Local\\Programs\\Python\\Python311\\DLLs', 'c:\\Users\\carol\\AppData\\Local\\Programs\\Python\\Python311\\Lib', 'c:\\Users\\carol\\AppData\\Local\\Programs\\Python\\Python311', '', 'C:\\Users\\carol\\AppData\\Roaming\\Python\\Python311\\site-packages', 'C:\\Users\\carol\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32', 'C:\\Users\\carol\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32\\lib', 'C:\\Users\\carol\\AppData\\Roaming\\Python\\Python311\\site-packages\\Pythonwin', 'c:\\Users\\carol\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages', '/Classification/', '/Classification', '/Classification', '/Classification/', '.\\Classification', 'c:\\Users\\carol\\Documents\\IPCV-MASTER\\TRDP\\Code\\SalUn_study\\My_tests/Classification', 'c:\\Users\\carol\\Documents\\IPCV-MASTER\\TRDP\\Code\\SalUn_study\\My_tests\\Classification', 'c:\\Users\\carol\

In [ ]:
import arg_parser as ap 

from generate_mask import generate_mask_f
args = generate_mask_f()

usage: ipykernel_launcher.py [-h] [--data DATA] [--dataset DATASET]
                             [--input_size INPUT_SIZE] [--data_dir DATA_DIR]
                             [--num_workers NUM_WORKERS]
                             [--num_classes NUM_CLASSES] [--arch ARCH]
                             [--imagenet_arch] [--train_y_file TRAIN_Y_FILE]
                             [--val_y_file VAL_Y_FILE] [--seed SEED]
                             [--train_seed TRAIN_SEED] [--gpu GPU]
                             [--workers WORKERS] [--resume]
                             [--checkpoint CHECKPOINT] [--save_dir SAVE_DIR]
                             [--model_path MODEL_PATH]
                             [--batch_size BATCH_SIZE] [--lr LR]
                             [--momentum MOMENTUM]
                             [--weight_decay WEIGHT_DECAY] [--epochs EPOCHS]
                             [--warmup WARMUP] [--print_freq PRINT_FREQ]
                             [--decreasing_lr DECREASING

SystemExit: 2

C:\Users\carol\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [222]:
proj_path = os.getcwd().split('\\')[:-1]
print(proj_path)
print('/'.join(proj_path) + 'My_tests/')

['c:', 'Users', 'carol', 'Documents', 'IPCV-MASTER', 'TRDP', 'Code', 'SalUn_study']
c:/Users/carol/Documents/IPCV-MASTER/TRDP/Code/SalUn_studyMy_tests/


In [169]:
print(splitted['Train_retain'][0])

(tensor([[[ 0.5193,  0.0398, -0.3198,  ..., -0.5596, -0.6281, -0.7650],
         [ 0.2796,  0.3652,  0.0227,  ..., -0.4739, -0.7993, -0.9020],
         [ 0.2796,  0.2624, -0.1486,  ..., -0.7650, -0.9534, -0.9705],
         ...,
         [ 0.8789,  0.5536,  0.5193,  ..., -1.3987, -1.0733, -0.5253],
         [ 0.7077,  0.5536,  0.6049,  ..., -0.3541, -0.0116,  0.1254],
         [ 0.6734,  0.5878,  0.6734,  ...,  0.3309,  0.3309,  0.3309]],

        [[ 1.0630,  0.3627, -0.2150,  ..., -0.3725, -0.4601, -0.6176],
         [ 0.7654,  0.6429,  0.1527,  ..., -0.3025, -0.6352, -0.7577],
         [ 0.6779,  0.5203, -0.0224,  ..., -0.6001, -0.8102, -0.8277],
         ...,
         [ 0.8880,  0.6604,  0.7654,  ..., -1.4405, -1.1078, -0.5826],
         [ 0.6604,  0.6254,  0.7829,  ..., -0.4076, -0.0399,  0.0826],
         [ 0.5553,  0.5553,  0.6954,  ...,  0.2927,  0.3102,  0.2927]],

        [[ 1.4548,  0.5659, -0.1487,  ..., -0.5670, -0.5670, -0.5844],
         [ 1.1411,  0.8797,  0.2522,  ..., -

In [170]:
print(splitted['Train_forget'][0])

(tensor([[[-1.1075, -1.3815, -1.2617,  ...,  0.5878,  0.4851,  0.4166],
         [-1.8439, -2.1179, -1.8097,  ..., -0.0116, -0.0801, -0.0287],
         [-1.6898, -1.8439, -1.2788,  ..., -0.0972, -0.0629, -0.2513],
         ...,
         [ 1.4440,  1.3242,  1.2728,  ...,  0.6221, -1.1589, -1.2103],
         [ 0.9646,  0.8447,  1.0673,  ...,  1.0331, -0.4568, -0.6965],
         [ 0.9132,  0.7591,  0.9474,  ...,  1.5810,  0.4679, -0.0116]],

        [[-0.9503, -1.2304, -1.1954,  ...,  0.2752,  0.1527,  0.1352],
         [-1.6856, -2.0357, -1.8957,  ..., -0.4951, -0.5826, -0.5126],
         [-1.6155, -1.9132, -1.5630,  ..., -0.5651, -0.5651, -0.7577],
         ...,
         [ 0.9405,  0.6429,  0.7829,  ...,  0.2927, -1.4930, -1.4405],
         [ 0.3978,  0.1176,  0.4853,  ...,  0.5553, -0.9503, -1.1078],
         [ 0.4853,  0.2227,  0.4503,  ...,  1.1856,  0.0301, -0.4251]],

        [[-0.7064, -1.0201, -1.0550,  ...,  0.0779, -0.0267, -0.0092],
         [-1.4559, -1.8044, -1.8044,  ..., -

In [134]:
print(splitted['Train'][0])

(tensor([[[-1.1075, -1.3815, -1.2617,  ...,  0.5878,  0.4851,  0.4166],
         [-1.8439, -2.1179, -1.8097,  ..., -0.0116, -0.0801, -0.0287],
         [-1.6898, -1.8439, -1.2788,  ..., -0.0972, -0.0629, -0.2513],
         ...,
         [ 1.4440,  1.3242,  1.2728,  ...,  0.6221, -1.1589, -1.2103],
         [ 0.9646,  0.8447,  1.0673,  ...,  1.0331, -0.4568, -0.6965],
         [ 0.9132,  0.7591,  0.9474,  ...,  1.5810,  0.4679, -0.0116]],

        [[-0.9503, -1.2304, -1.1954,  ...,  0.2752,  0.1527,  0.1352],
         [-1.6856, -2.0357, -1.8957,  ..., -0.4951, -0.5826, -0.5126],
         [-1.6155, -1.9132, -1.5630,  ..., -0.5651, -0.5651, -0.7577],
         ...,
         [ 0.9405,  0.6429,  0.7829,  ...,  0.2927, -1.4930, -1.4405],
         [ 0.3978,  0.1176,  0.4853,  ...,  0.5553, -0.9503, -1.1078],
         [ 0.4853,  0.2227,  0.4503,  ...,  1.1856,  0.0301, -0.4251]],

        [[-0.7064, -1.0201, -1.0550,  ...,  0.0779, -0.0267, -0.0092],
         [-1.4559, -1.8044, -1.8044,  ..., -